# Generated by Django 4.2 on 2023-05-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('AL', 'All'), ('FA', 'Fantasy'), ('SF', 'Science Fiction'), ('DY', 'Dystopian'), ('AA', 'Action & Adventure'), ('MY', 'Mystery'), ('HO', 'Horror'), ('TH', 'Thriller & Suspense'), ('HF', 'Historical Fiction'), ('RO', 'Romance'), ('ME', 'Memoir & Autobiography'), ('BI', 'Biography'), ('FD', 'Food & Drinks'), ('AP', 'Art & Photography'), ('SH', 'Self Help'), ('HI', 'History'), ('TR', 'Travel'), ('TC', 'True Crime'), ('HU', 'Humor'), ('ES', 'Essay'), ('GU', 'Guide'), ('RS', 'Religion & Spirituality'), ('HS', 'Humanities & Social sciences'), ('PA', 'Parenting & Families'), ('ST', 'Science & Technology'), ('CH', "Children's"), ('UN', 'Unknown')], default='UN', max_length=2),
        ),
    ]
