# Generated by Django 4.2 on 2023-05-02 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('inscription_date', models.DateField(auto_now_add=True)),
                ('city_address', models.CharField(max_length=100)),
                ('postal_code_address', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{5}', 'Enter a valid postal code')])),
                ('street_address', models.CharField(max_length=100)),
                ('street_num_address', models.IntegerField()),
                ('street_num_comp', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^0[0-9]([ .-/]?[0-9]{2}){4}$', 'Enter a valid phone number.')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('SE', 'Sent'), ('AR', 'Arrived')], default='CR', max_length=2)),
                ('city_address', models.CharField(max_length=100)),
                ('postal_code_address', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Enter a valid postal code')])),
                ('street_address', models.CharField(max_length=100)),
                ('street_num_address', models.IntegerField()),
                ('street_num_comp', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('books', models.ManyToManyField(to='catalog.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 'Very Bad'), (1, 'Bad'), (2, 'Okay'), (3, 'Good'), (4, 'Very Good'), (5, 'Awesome')], default=5)),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('city_address', models.CharField(max_length=100)),
                ('postal_code_address', models.IntegerField(validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Enter a valid postal code')])),
                ('street_address', models.CharField(max_length=100)),
                ('street_num_address', models.IntegerField()),
                ('street_num_comp', models.CharField(max_length=100)),
                ('shipping_choice', models.CharField(choices=[('NO', 'Normal'), ('FA', 'Fast'), ('OD', 'One day')], default='NO', max_length=2)),
                ('price', models.FloatField()),
                ('books', models.ManyToManyField(to='catalog.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
